routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('factory', 'Manage\FactoryController');

    Route::resource('buyer', 'Manage\BuyerController');
    Route::get('buyer-list/{buyer}', 'Manage\BuyerController@factoryBuyer')->name('buyer.list');

    Route::resource('style', 'Manage\StyleController');
    Route::get('style-list', 'Manage\StyleController@styleList')->name('style.list');

    Route::resource('colour', 'Manage\ColourController');
    Route::get('colour-list', 'Manage\ColourController@colourList')->name('colour.list');

    Route::resource('order', 'OrderController');
    Route::get('batch-order/{data}', 'OrderController@batchOrder')->name('batch.order');
    Route::get('lab-order/{data}', 'OrderController@labOrder')->name('lab.order');
    Route::get('order-entry', 'OrderController@newOrder')->name('order.entry');
    Route::get('simple-order/{data}', 'OrderController@simpleOrder')->name('simple.order');
    Route::get('grey-order/{data}', 'OrderController@greyOrder')->name('grey.order');

    Route::resource('user', 'UserController');
    Route::put('user-password/{data}', 'UserController@ProfilePassword')->name('user.password');
    Route::get('user-manage', 'UserController@UserManage')->name('UserManage');
    Route::get('/user-delete/{user}', 'Auth\RegisterController@delete')->name('UserDelete');
    Route::post('register', 'Auth\RegisterController@register')->name('register');

    Route::get('/role', 'UserController@role')->name('role');
    Route::post('/role', 'UserController@RoleStore')->name('role.store');
    Route::get('role/{role}', 'UserController@RoleDestroy')->name('role.delete');
    Route::get('role/{role}/edit', 'UserController@RoleEdit')->name('role.edit');
    Route::put('role/{role}', 'UserController@RoleUpdate')->name('role.update');

    Route::get('/role-permission', 'UserController@RolePermission')->name('role.permission');
    Route::post('/role-permission-store', 'UserController@RolePermissionStore')->name('RolePermissionStore');

    Route::get('/profile-edit/{data}/edit', 'UserController@ProfileEdit')->name('ProfileEdit');
    Route::post('/profile-update/{data}', 'Auth\RegisterController@ProfileUpdate')->name('ProfileUpdate');
    Route::post('/profile-password-change/{data}', 'Auth\RegisterController@ProfilePasswordChange')->name('ProfilePasswordChange');

    Route::get('order-report', 'ReportController@orderReport')->name('report.order');
    Route::get('stock-report', 'ReportController@stockReport')->name('report.stock');
    Route::get('color-report', 'ReportController@colorReport')->name('report.color');

    Route::resource('batch', 'BatchController');
    Route::get('batch-entry', 'BatchController@newBatch')->name('batch.entry');
    Route::get('get-batch/{data}', 'BatchController@getBatch')->name('batch.get');

    Route::resource('grey', 'GreyController');
    Route::get('grey-entry', 'GreyController@newGrey')->name('grey.entry');
    Route::get('get-grey/{data}', 'GreyController@getGrey')->name('grey.get');

    Route::resource('process', 'Manage\ProcessController');
    Route::resource('process-entry', 'ProcessController');

    Route::resource('finished', 'FinishedController');
    Route::get('finished-entry', 'FinishedController@newFinished')->name('finished.entry');

    Route::resource('Lab', 'LabController');
    Route::get('Lab-entry', 'LabController@newLab')->name('lab.entry');

    Route::resource('delivery', 'DeliveryController');
    Route::get('delivery-entry', 'DeliveryController@newDelivery')->name('delivery.entry');

    Route::get('delivery-challan/{data}', 'DeliveryController@deliveryChallan')->name('delivery.challan');

    Route::resource('bill', 'BillController');
    Route::get('bill-entry', 'BillController@newBillEntry')->name('bill.entry');

    Route::get('delivery-bill/{data}', 'BillController@billChallan')->name('bill.challan');

});

resources/views/finished.blade.php
@extends('layouts.app')
@section('title','Dyeing Factory')
@section('content')
    @if ($errors->any())
        @foreach ($errors->all() as $error)
            <div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <i class="fa fa-times-circle mx-2"></i>
                <strong>Error!</strong> {{$error}}!
            </div>
        @endforeach
    @endif
    @if(session()->has('message'))
        <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <i class="fa fa-check mx-2"></i>
            <strong>Success!</strong> {{ session()->get('message') }}!
        </div>
    @endif
    <div class="main-content-container container-fluid px-4 mb-4">
        <!-- Page Header -->
        <div class="page-header row no-gutters py-4">
            <div class="col-12 col-sm-6 text-center text-sm-left mb-4 mb-sm-0">
                <span class="text-uppercase page-subtitle"></span>
                <h3 class="page-title">Finished Receive</h3>
            </div>
            <div class="col-12 col-sm-6 d-flex align-items-center">
                <div class="d-inline-flex mb-sm-0 mx-auto ml-sm-auto mr-sm-0" role="group" aria-label="Page actions">
                    <a id="add-new-event" href="{{route('finished.entry')}}" class="btn btn-primary">
                        <i class="material-icons">add</i> Finished Quantity Add</a>
                </div>
            </div>
        </div>
        <table class="transaction-history d-none">
            <thead>
            <tr>
                <th>#</th>
                <th>Factory Name</th>
                <th>Buyer Name</th>
                <th>Batch No.</th>
                <th>Order No.</th>
                <th>Grey Received</th>
                <th>Finished Quantity</th>
                <th>Waste</th>
            </tr>
            </thead>
            <tbody>@php $sl = 1; @endphp
            @foreach($finished as $finisheds)
                <tr>
                    <td>{{$sl}}</td>@php $sl++; @endphp
                    <td>{{$finisheds->order_list->order->factory->factory_name}}</td>
                    <td>{{$finisheds->order_list->buyer->buyer}}</td>
                    <td>{{$finisheds->batch->batch_no}}</td>
                    <td>{{$finisheds->order_list->order_id}}</td>
                    <td>{{$finisheds->grey_wt}}</td>
                    <td>{{$finisheds->finished_qty}}</td>
                    <td>{{$finisheds->waste}}</td>

                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection
@push('style')
    <link rel="stylesheet" href="{{asset('assets/styles/responsive.dataTables.min.css')}}"/>
    <link rel="stylesheet" href="{{asset('assets/sweetalert/sweetalert.css')}}"/>
@endpush
@push('script')
    <script src="{{asset('assets/scripts/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('assets/scripts/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('assets/scripts/app/app-transaction-history.1.3.1.min.js')}}"></script>
    <script src="{{asset('assets/sweetalert/sweetalert.js')}}"></script>
    <script>
        $('.datepicker').datepicker("setDate", new Date());
    </script>
@endpush

resources/views/home.blade.php
@extends('layouts.app')
@section('title','Dyeing Factory')
@section('content')
    <div class="main-content-container container-fluid px-4">
        <!-- Page Header -->
        <div class="page-header row no-gutters py-4">
            <div class="col-12 col-sm-4 text-center text-sm-left mb-4 mb-sm-0">
                <span class="text-uppercase page-subtitle">Dashboard</span>
                <h3 class="page-title"></h3>
            </div>
        </div>
        <!-- End Page Header -->

    </div>
@endsection
@push('style')

@endpush
@push('script')
    <script src="{{asset('assets/scripts/app/app-ecommerce.1.3.1.min.js')}}"></script>
@endpush

resources/views/order.blade.php
@extends('layouts.app')
@section('title','Dyeing Factory')
@section('content')
    @if ($errors->any())
        @foreach ($errors->all() as $error)
            <div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <i class="fa fa-times-circle mx-2"></i>
                <strong>Error!</strong> {{$error}}!
            </div>
        @endforeach
    @endif
    @if(session()->has('message'))
        <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <i class="fa fa-check mx-2"></i>
            <strong>Success!</strong> {{ session()->get('message') }}!
        </div>
    @endif
    <div class="main-content-container container-fluid px-4 mb-4">
        <!-- Page Header -->
        <div class="page-header row no-gutters py-4">
            <div class="col-12 col-sm-6 text-center text-sm-left mb-4 mb-sm-0">
                <span class="text-uppercase page-subtitle"></span>
                <h3 class="page-title">Order List</h3>
            </div>
            <div class="col-12 col-sm-6 d-flex align-items-center">
                <div class="d-inline-flex mb-sm-0 mx-auto ml-sm-auto mr-sm-0" role="group" aria-label="Page actions">
                    <a href="{{route('order.entry')}}" class="btn btn-primary">
                        <i class="material-icons">add</i> New Order Entry</a>
                </div>
            </div>
        </div>
        <table class="transaction-history d-none">
            <thead>
            <tr>
                <th>#</th>
                <th>Factory Name</th>
                <th>Order No</th>
                <th>Total Quantity</th>
                <th>Date</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>@php $sl = 1; @endphp
            @foreach($order as $orders)
                <tr>
                    <td>{{$sl}}</td>@php $sl++; @endphp
                    <td>{{$orders->factory->factory_name}}</td>
                    <td>{{$orders->id}}</td>
                    <td>{{$orders->total_qty}}</td>
                    <td>{{$orders->date}}</td>
                    <td>
                        <div class="btn-group btn-group-sm" role="group">
                            <button type="button" class="btn btn-white view" id="{{$orders->id}}">
                                <i class="material-icons">
                                    remove_red_eye
                                </i>
                            </button>
                            <button type="button" class="btn btn-white delete"
                                    href="{{route('order.destroy',$orders->id)}}">
                                <i class="material-icons">&#xE872;</i>
                            </button>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    <!-- Modal -->
    <div class="modal fade bd-example-modal-lg" id="exampleModal" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <div>
                        <h4 class="text-center mb-0">Dyeing Factory</h4>
                        <p class="text-center">Dhaka Bangladesh</p>
                        <hr>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <table class="table border">
                                <tr>
                                    <td>Factory Name:</td>
                                    <td>
                                        <span class="factory_id"></span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Factory Address:</td>
                                    <td>
                                        <span class="factory_address"></span>
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-md-6">
                            <table class="table border">
                                <tr>
                                    <td>Date:</td>
                                    <td>
                                        <span class="date"></span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Total Qty:</td>
                                    <td>
                                        <span class="total_qty"></span>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-bordered mb-0 mt-4 text-center" style="width: 200%">
                            <thead class="bg-light">
                            <tr>
                                <th scope="col" style="white-space: nowrap">Order List No</th>
                                <th scope="col" style="white-space: nowrap">Buyer Name</th>
                                <th scope="col" style="white-space: nowrap">Style</th>
                                <th scope="col" style="white-space: nowrap">Work Order</th>
                                <th scope="col" style="white-space: nowrap">Yarn Count</th>
                                <th scope="col" style="white-space: nowrap">Fabrics Type</th>
                                <th scope="col" style="white-space: nowrap">MC/DIA</th>
                                <th scope="col" style="white-space: nowrap">F/DIA</th>
                                <th scope="col" style="white-space: nowrap">Grey GSM/S/L</th>
                                <th scope="col" style="white-space: nowrap">F/GSM</th>
                                <th scope="col" style="white-space: nowrap">Color</th>
                                <th scope="col" style="white-space: nowrap">Quantity</th>
                            </tr>
                            </thead>
                            <tbody class="AddPurchaseDiv">

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('style')
    <link rel="stylesheet" href="{{asset('assets/styles/responsive.dataTables.min.css')}}"/>
    <link rel="stylesheet" href="{{asset('assets/sweetalert/sweetalert.css')}}"/>
@endpush
@push('script')
    <script src="{{asset('assets/scripts/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('assets/scripts/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('assets/scripts/app/app-transaction-history.1.3.1.min.js')}}"></script>
    <script src="{{asset('assets/sweetalert/sweetalert.js')}}"></script>
    <script>
        $(document).on('click', '.view', function () {
            let id = $(this).attr("id");
            $.ajax({
                url: "{!! route('order.show','') !!}" + "/" + id,
                type: 'get',
                dataType: 'json',
                success: function (data) {
                    $('.factory_id').html(data.order.factory.factory_name);
                    $('.factory_address').html(data.order.factory.address);
                    $('.date').html(data.order.date);
                    $('.total_qty').html(data.order.total_qty);
                    $(".AddPurchaseDiv").html('');
                    for (let i = 0; i < data.order.order_list.length; i++) {
                        var style, colour;
                        if (data.order.order_list[i].style == null) {
                            style = ''
                        } else {
                            style = data.order.order_list[i].style.style_name
                        }
                        if (data.order.order_list[i].colour == null) {
                            colour = ''
                        } else {
                            colour = data.order.order_list[i].colour.colour_name
                        }
                        let product = '<tr>\n' +
                            '                                        <td>' + data.order.order_list[i].id + '</td>\n' +
                            '                                        <td>' + data.order.order_list[i].buyer.buyer + '</td>\n' +
                            '                                        <td>' + style + '</td>\n' +
                            '                                        <td>' + data.order.order_list[i].work_order + '</td>\n' +
                            '                                        <td>' + data.order.order_list[i].yarn_count + '</td>\n' +
                            '                                        <td>' + data.order.order_list[i].fabrics_type + '</td>\n' +
                            '                                        <td>' + data.order.order_list[i].dia + '</td>\n' +
                            '                                        <td>' + data.order.order_list[i].f_dia + '</td>\n' +
                            '                                        <td>' + data.order.order_list[i].gray_gsm + '</td>\n' +
                            '                                        <td>' + data.order.order_list[i].gsm + '</td>\n' +
                            '                                        <td>' + colour + '</td>\n' +
                            '                                        <td>' + data.order.order_list[i].quantity + '</td>\n' +
                            '                                    </tr>';
                        $(".AddPurchaseDiv").append(product);
                        removenull();
                    }
                    $('#exampleModal').modal('show');
                }
            });
        });

        function removenull() {
            $(".AddPurchaseDiv tr td")
                .filter(function (index) {
                    if ($(this).text() == 'null') {
                        return true;
                    }
                })
                .text('');
        }

        $(document).on('click', '.delete', function (e) {
            e.preventDefault();
            let linkURL = $(this).attr("href");
            swal({
                title: "Sure want to delete?",
                text: "If you click 'OK' file will be deleted",
                type: "warning",
                showCancelButton: true
            }, function () {
                $.ajax({
                    type: "DELETE",
                    url: linkURL,
                    data: {_token: $('meta[name="csrf-token"]').attr('content')},
                    success: function (result) {
                        swal({
                            title: "Well Done",
                            text: "Order has been delete successfully",
                            type: "success",
                        }, function () {
                            location.reload();
                        })
                    },
                    error: function (result) {
                        if (result.status == 401) {
                            swal({
                                title: result.responseJSON.status,
                                text: result.responseJSON.message,
                                type: "warning",
                            })
                        } else {
                            swal({
                                title: "Something Wrong",
                                text: "Please try again later",
                                type: "warning",
                            })
                        }
                    }
                });
            });
        });
    </script>
@endpush

resources/views/process_entry.blade.php
@extends('layouts.app')
@section('title','Dyeing Factory')
@section('content')
    @if ($errors->any())
        @foreach ($errors->all() as $error)
            <div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <i class="fa fa-times-circle mx-2"></i>
                <strong>Error!</strong> {{$error}}!
            </div>
        @endforeach
    @endif
    @if(session()->has('message'))
        <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <i class="fa fa-check mx-2"></i>
            <strong>Success!</strong> {{ session()->get('message') }}!
        </div>
    @endif
    <div class="main-content-container container-fluid px-4 mb-4">
        <!-- Page Header -->
        <div class="page-header row no-gutters py-4">
            <div class="col-12 col-sm-6 text-center text-sm-left mb-4 mb-sm-0">
                <span class="text-uppercase page-subtitle"></span>
                <h3 class="page-title">Process Entry</h3>
            </div>
            <div class="col-12 col-sm-6 d-flex align-items-center">
                <div class="d-inline-flex mb-sm-0 mx-auto ml-sm-auto mr-sm-0" role="group" aria-label="Page actions">
                    <a id="add-new-event" role="button" href="#" class="btn btn-primary" data-toggle="modal"
                       data-target="#exampleModal">
                        <i class="material-icons">add</i> New Process Add</a>
                </div>
            </div>
        </div>
        <table class="transaction-history d-none">
            <thead>
            <tr>
                <th>#</th>
                <th>Factory Name</th>
                <th>Batch No.</th>
                <th>Order No.</th>
                <th>Process Name</th>
                <th>Created</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>@php $sl = 1; @endphp
            @foreach($process_list as $process_lists)
                <tr>
                    <td>{{$sl}}</td>@php $sl++; @endphp
                    <td>{{$process_lists->batch->order->factory->factory_name}}</td>
                    <td>{{$process_lists->batch->batch_no}}</td>
                    <td>{{$process_lists->batch->order_id}}</td>
                    <td>
                        @foreach(get_process($process_lists->process_id) as $processes)
                            <span class="badge badge-primary m-1">{{$processes->process_name}}</span>
                        @endforeach
                    </td>
                    <td>{{$process_lists->created_at->format('d-M-Y')}}</td>
                    <td>
                        <div class="btn-group btn-group-sm" role="group" aria-label="Table row actions">
                            <button type="button" class="btn btn-white delete"
                                    href="{{route('process-entry.destroy',$process_lists->id)}}">
                                <i class="material-icons">&#xE872;</i>
                            </button>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <form method="post" action="{{route('process-entry.store')}}" autocomplete="off">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Add process in batch</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        @csrf
                        <div class="form-row">
                            <div class="col-3">Batch No:</div>
                            <div class="form-group col-6">
                                <input type="number" class="form-control batch_no"
                                       placeholder="Enter Batch No">
                                <div class="invalid-feedback"></div>
                            </div>
                            <div class="col-3 text-right">
                                <button type="button" class="btn btn-primary search">Search</button>
                            </div>
                        </div>
                        <div class="modal_div" style="display: none">
                            <strong class="text-muted d-block mb-2">Select process:</strong>
                            <input type="hidden" class="batch_id" name="batch_id">
                            <div class="form-row">
                                @foreach($process as $processes)
                                    <div class="form-group col-md-6">
                                        <div class="custom-control custom-checkbox mb-1">
                                            <input type="checkbox" name="process[]" value="{{$processes->id}}"
                                                   class="custom-control-input" id="formsAgreeField{{$processes->id}}">
                                            <label class="custom-control-label"
                                                   for="formsAgreeField{{$processes->id}}">{{$processes->process_name}}</label>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@push('style')
    <link rel="stylesheet" href="{{asset('assets/styles/responsive.dataTables.min.css')}}"/>
    <link rel="stylesheet" href="{{asset('assets/sweetalert/sweetalert.css')}}"/>
@endpush
@push('script')
    <script src="{{asset('assets/scripts/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('assets/scripts/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('assets/scripts/app/app-transaction-history.1.3.1.min.js')}}"></script>
    <script src="{{asset('assets/sweetalert/sweetalert.js')}}"></script>
    <script>
        $('.search').click(function (e) {
            e.preventDefault();
            let batch = $('.batch_no').val();
            $.ajax({
                url: "{!! route('batch.get','') !!}" + "/" + batch,
                type: 'get',
                dataType: 'json',
                success: function (result) {
                    $('.batch_no').removeClass('is-invalid');
                    $('.invalid-feedback').text('');
                    $('.batch_id').val(result.batch.id);
                    $('.modal_div').show();
                },
                error: function (result) {
                    $('.batch_no').addClass('is-invalid');
                    $('.invalid-feedback').text('No batch found');
                    $('.modal_div').hide();
                    $('.batch_id').val('');
                }
            });
        });


        $(document).on('click', '.delete', function (e) {
            e.preventDefault();
            let linkURL = $(this).attr("href");
            swal({
                title: "Sure want to delete?",
                text: "If you click 'OK' file will be deleted",
                type: "warning",
                showCancelButton: true
            }, function () {
                $.ajax({
                    type: "DELETE",
                    url: linkURL,
                    data: {_token: $('meta[name="csrf-token"]').attr('content')},
                    success: function (result) {
                        swal({
                            title: "Well Done",
                            text: "Batch process has been delete successfully",
                            type: "success",
                        }, function () {
                            location.reload();
                        })
                    },
                    error: function (result) {
                        if (result.status == 401) {
                            swal({
                                title: "Can't Delete",
                                text: "You already create nothing",
                                type: "warning",
                            })
                        } else {
                            swal({
                                title: "Something Wrong",
                                text: "Please try again later",
                                type: "warning",
                            })
                        }
                    }
                });
            });
        });

        $('.edit').click(function (e) {
            let linkURL = $(this).attr("href");
            window.location.href = linkURL;
        });
    </script>
@endpush