routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('factory', 'Manage\FactoryController');

    Route::resource('buyer', 'Manage\BuyerController');
    Route::get('buyer-list/{buyer}', 'Manage\BuyerController@factoryBuyer')->name('buyer.list');

    Route::resource('style', 'Manage\StyleController');
    Route::get('style-list', 'Manage\StyleController@styleList')->name('style.list');

    Route::resource('colour', 'Manage\ColourController');
    Route::get('colour-list', 'Manage\ColourController@colourList')->name('colour.list');

    Route::resource('order', 'OrderController');
    Route::get('batch-order/{data}', 'OrderController@batchOrder')->name('batch.order');
    Route::get('lab-order/{data}', 'OrderController@labOrder')->name('lab.order');
    Route::get('order-entry', 'OrderController@newOrder')->name('order.entry');
    Route::get('simple-order/{data}', 'OrderController@simpleOrder')->name('simple.order');
    Route::get('grey-order/{data}', 'OrderController@greyOrder')->name('grey.order');

    Route::resource('user', 'UserController');
    Route::put('user-password/{data}', 'UserController@ProfilePassword')->name('user.password');
    Route::get('user-manage', 'UserController@UserManage')->name('UserManage');
    Route::get('/user-delete/{user}', 'Auth\RegisterController@delete')->name('UserDelete');
    Route::post('register', 'Auth\RegisterController@register')->name('register');

    Route::get('/role', 'UserController@role')->name('role');
    Route::post('/role', 'UserController@RoleStore')->name('role.store');
    Route::get('role/{role}', 'UserController@RoleDestroy')->name('role.delete');
    Route::get('role/{role}/edit', 'UserController@RoleEdit')->name('role.edit');
    Route::put('role/{role}', 'UserController@RoleUpdate')->name('role.update');

    Route::get('/role-permission', 'UserController@RolePermission')->name('role.permission');
    Route::post('/role-permission-store', 'UserController@RolePermissionStore')->name('RolePermissionStore');

    Route::get('/profile-edit/{data}/edit', 'UserController@ProfileEdit')->name('ProfileEdit');
    Route::post('/profile-update/{data}', 'Auth\RegisterController@ProfileUpdate')->name('ProfileUpdate');
    Route::post('/profile-password-change/{data}', 'Auth\RegisterController@ProfilePasswordChange')->name('ProfilePasswordChange');

    Route::get('order-report', 'ReportController@orderReport')->name('report.order');
    Route::get('stock-report', 'ReportController@stockReport')->name('report.stock');
    Route::get('color-report', 'ReportController@colorReport')->name('report.color');

    Route::resource('batch', 'BatchController');
    Route::get('batch-entry', 'BatchController@newBatch')->name('batch.entry');
    Route::get('get-batch/{data}', 'BatchController@getBatch')->name('batch.get');

    Route::resource('grey', 'GreyController');
    Route::get('grey-entry', 'GreyController@newGrey')->name('grey.entry');
    Route::get('get-grey/{data}', 'GreyController@getGrey')->name('grey.get');

    Route::resource('process', 'Manage\ProcessController');
    Route::resource('process-entry', 'ProcessController');

    Route::resource('finished', 'FinishedController');
    Route::get('finished-entry', 'FinishedController@newFinished')->name('finished.entry');

    Route::resource('Lab', 'LabController');
    Route::get('Lab-entry', 'LabController@newLab')->name('lab.entry');

    Route::resource('delivery', 'DeliveryController');
    Route::get('delivery-entry', 'DeliveryController@newDelivery')->name('delivery.entry');

    Route::get('delivery-challan/{data}', 'DeliveryController@deliveryChallan')->name('delivery.challan');

    Route::resource('bill', 'BillController');
    Route::get('bill-entry', 'BillController@newBillEntry')->name('bill.entry');

    Route::get('delivery-bill/{data}', 'BillController@billChallan')->name('bill.challan');

});

resources/views/inc/footer.blade.php
<footer class="main-footer d-flex p-2 px-3 bg-white border-top">
    <span class="copyright ml-auto my-auto mr-2">Copyright © 2020 Dyeing Factory, Dhaka Bangladesh.</span>
</footer>

resources/views/inc/header.blade.php
<div class="main-navbar sticky-top bg-white">
    <!-- Main Navbar -->
    <nav class="navbar align-items-stretch navbar-light flex-md-nowrap p-0">
        <ul class="nav main-navbar__search w-100 d-none d-md-flex d-lg-flex py-2">
            <li class="nav-item">
                <a class="nav-link" style="color: #3d5170" href="{{route('report.order')}}">Order Report</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color: #3d5170" href="{{route('report.stock')}}">Stock Report</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color: #3d5170" href="{{route('report.color')}}">Color Report</a>
            </li>
        </ul>
        <ul class="navbar-nav border-left flex-row ">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-nowrap px-3" data-toggle="dropdown" href="#"
                   role="button" aria-haspopup="true" aria-expanded="false">
                    <img class="user-avatar rounded-circle mr-2" src="{{asset(Auth::user()->image)}}"
                         alt="User Avatar" style="height: 2.5rem!important;"> <span
                        class="d-none d-md-inline-block">{{Auth::user()->name}}</span>
                </a>
                <div class="dropdown-menu dropdown-menu-small" style="left: 0!important;">
                    <a class="dropdown-item" href="{{route('user.index')}}"><i class="material-icons"></i> Profile</a>
                    @if(user_has_permission(Auth::user()->id, 1))
                        <a class="dropdown-item" href="{{route('UserManage')}}"><i class="material-icons"></i> User
                            Management</a>
                        <a class="dropdown-item" href="{{route('role')}}"><i class="material-icons"></i> Role</a>
                        <a class="dropdown-item" href="{{route('role.permission')}}"><i class="material-icons"></i>
                            Role
                            Permission</a>
                    @endif
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item text-danger" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();" href="/">
                        <i class="material-icons text-danger"></i> Logout </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST"
                          style="display: none;">
                        @csrf
                        <input type="hidden" name="type" value="admin">
                    </form>
                </div>
            </li>
        </ul>
        <nav class="nav">
            <a href="#"
               class="nav-link nav-link-icon toggle-sidebar d-sm-inline d-md-none text-center border-left"
               data-toggle="collapse" data-target=".header-navbar" aria-expanded="false"
               aria-controls="header-navbar">
                <i class="material-icons">&#xE5D2;</i>
            </a>
        </nav>
    </nav>
</div> <!-- / .main-navbar -->

resources/views/inc/sidebar.blade.php
<!-- Main Sidebar -->
<aside class="main-sidebar col-12 col-md-3 col-lg-2 px-0" style="z-index: 1040">
    <div class="main-navbar">
        <nav class="navbar align-items-stretch navbar-light bg-white flex-md-nowrap border-bottom p-0">
            <a class="navbar-brand w-100 mr-0" href="{{route('home')}}" style="line-height: 25px;">
                <div class="d-table m-auto">

                    <span class="d-none d-md-inline ml-1 font-weight-bold" style="font-family: 'Chilanka', cursive;">Yarn Museum</span>
                </div>
            </a>
            <a class="toggle-sidebar d-sm-inline d-md-none d-lg-none">
                <i class="material-icons">&#xE5C4;</i>
            </a>
        </nav>
    </div>
    <div class="nav-wrapper" style="overflow-y: auto;">
        <ul class="nav nav--no-borders flex-column">
            <li class="nav-item">
                <a class="nav-link {{Route::current()->getName() == 'home'?'active':''}}" href="{{route('home')}}">
                    <i class="material-icons"></i>
                    <span>Dashboards</span>
                </a>
            </li>
            <li class="nav-item dropdown {{user_has_permission(Auth::user()->id, 2)?'':'d-none'}}">
                <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="#" role="button" aria-haspopup="false"
                   aria-expanded="false">
                    <i class="material-icons"></i>
                    <span>Dyeing Manage</span>
                </a>
                <div class="dropdown-menu dropdown-menu-small">
                    <a class="dropdown-item " href="{{route('factory.index')}}">Factory Entry</a>
                    <a class="dropdown-item " href="{{route('buyer.index')}}">Buyer Entry</a>
                    <a class="dropdown-item " href="{{route('style.index')}}">Style Entry</a>
                    <a class="dropdown-item " href="{{route('colour.index')}}">Colour Entry</a>
                    <a class="dropdown-item " href="{{route('process.index')}}">Process Entry</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Route::current()->getName() == 'order.index'?'active':''}} {{user_has_permission(Auth::user()->id, 3)?'':'d-none'}}"
                   href="{{route('order.index')}}">
                    <i class="material-icons"></i>
                    <span>Order Receive</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Route::current()->getName() == 'grey.index'?'active':''}} {{user_has_permission(Auth::user()->id, 4)?'':'d-none'}}"
                   href="{{route('grey.index')}}">
                    <i class="material-icons"></i>
                    <span>Grey Receive</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Route::current()->getName() == 'Lab.index'?'active':''}} {{user_has_permission(Auth::user()->id, 5)?'':'d-none'}}"
                   href="{{route('Lab.index')}}">
                    <i class="material-icons"></i>
                    <span>LAB Entry</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Route::current()->getName() == 'batch.index'?'active':''}} {{user_has_permission(Auth::user()->id, 6)?'':'d-none'}}"
                   href="{{route('batch.index')}}">
                    <i class="material-icons"></i>
                    <span>Batch</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Route::current()->getName() == 'process-entry.index'?'active':''}} {{user_has_permission(Auth::user()->id, 7)?'':'d-none'}}"
                   href="{{route('process-entry.index')}}">
                    <i class="material-icons"></i>
                    <span>Process</span>
                </a>
            </li>
            {{--            <li class="nav-item">--}}
            {{--                <a class="nav-link {{Route::current()->getName() == 'finished.index'?'active':''}}" href="{{route('finished.index')}}">--}}
            {{--                    <i class="material-icons"></i>--}}
            {{--                    <span>Finished Receive</span>--}}
            {{--                </a>--}}
            {{--            </li>--}}
            <li class="nav-item">
                <a class="nav-link {{Route::current()->getName() == 'delivery.index'?'active':''}} {{user_has_permission(Auth::user()->id, 8)?'':'d-none'}}"
                   href="{{route('delivery.index')}}">
                    <i class="material-icons"></i>
                    <span>Delivery Challan</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{Route::current()->getName() == 'bill.index'?'active':''}} {{user_has_permission(Auth::user()->id, 9)?'':'d-none'}}"
                   href="{{route('bill.index')}}">
                    <i class="material-icons"></i>
                    <span>Bill</span>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle " data-toggle="dropdown" href="#" role="button" aria-haspopup="false"
                   aria-expanded="false">
                    <i class="material-icons"></i>
                    <span>Report</span>
                </a>
                <div class="dropdown-menu dropdown-menu-small">
                    <a class="dropdown-item " href="{{route('report.order')}}">Order Report</a>
                    <a class="dropdown-item " href="{{route('report.stock')}}">Stock Report</a>
                </div>
            </li>
        </ul>

    </div>
</aside>
<!-- End Main Sidebar -->